---
title: "0622_R 시각화"
output:
  html_document:
    keep_md: true
date: '2022-06-22'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
 # install.packages("ggplot2")
 # install.packages("readxl")
```
## ggplot2 강의
- 데이터 불러오기
- aes = 축
- 오류 시 +후 한칸 뛰고 그래프 종류 작성
- 그래프 색상 변화 다양한 색 참고 (https://color.adobe.com/ko/create/color-wheel)
```{r}
library(readxl)
library("ggplot2")
who_disease <- read_xlsx("who_disease.xlsx")

# 기본 시각화
ggplot(who_disease, aes(x = year, y = cases)) +
  geom_point()
# 옵션 1 투명도 주기
ggplot(who_disease, aes(x = year, y = cases)) +
  geom_point(alpha = 0.1)
# 옵션 2 색상 변화
ggplot(who_disease, aes(x = year, y = cases)) +
  geom_point(alpha = 0.1, color = "#EB3BD9")

?geom_point
```
- colour 입력 위치
  + geom_point(colour =red) => 색상의 숫자가 들어가야함.
  + aes(x, y, colour = 컬럼명)
```{r}
str(iris)
ggplot(iris, aes(x = Sepal.Length, 
                 y = Sepal.Width,
                 colour = Petal.Length)) + geom_point()
```

- 산점도 : x축 수치형 연속형 데이터, y축 수치형 연속형 데이터 
- 
```{r}
ggplot(who_disease, aes(x = year, y = cases)) +
  geom_point(alpha = 0.1)
```
- 히스토그램 (분포가 어느 부분에 모여있는지 알아야 함.)
  + 질병 데이터 region = AMR, year = 1980, disease = 백일해(pertussis)
    cases > 0
```{r}
library(dplyr)
str(who_disease)
data2 <- who_disease %>% 
  filter(region == 'AMR',
         year == 1980,
         disease == 'pertussis',
         cases > 0) -> data2

ggplot(data2, aes(x = cases)) + 
  geom_histogram(fill = "red")
ggplot(data2, aes(x = country, y = cases)) + 
  geom_col(fill = "blue") +
  # 가로로 그래프 나타내기
  coord_flip()

ggplot(who_disease,aes(region)) +
  geom_bar()
ggplot(who_disease,aes(disease)) +
  geom_bar()
```
- 교재 풀기
## 산점도 그리기
```{r}
ggplot(data=diamonds,aes(x=carat, y=price)) + geom_point()
```
## 막대그래프 그리기
```{r}
ggplot(diamonds, aes(x=cut)) +geom_bar()
ggplot(diamonds, aes(x=cut, y= price)) + geom_bar(stat = "identity")

cut_price <-diamonds %>%
  group_by(cut) %>% 
  summarise(mean_price=mean(price))
ggplot(data = cut_price, aes(x = cut, y = mean_price)) + geom_col()
ggplot(data=diamonds, aes(x=carat)) + geom_histogram()
ggplot(data=diamonds, aes(x=carat)) + geom_histogram(binwidth = 1)
ggplot(data=diamonds, aes(x=carat)) + geom_histogram(binwidth = 0.1)
```
## 커널 밀도 곡선 그래프 만들기
```{r}
ggplot(data=diamonds, aes(x=carat)) + geom_density()
```
## 상자 그림 그래프 그리기
```{r}
ggplot(data=diamonds, aes(x=1, y=price)) + geom_boxplot()
ggplot(data=diamonds, aes(x=cut, y=price)) +geom_boxplot()
```
## 선그래프 그리기
```{r}
str(cars)
str(economics)
ggplot(data=cars,aes(x=speed, y=dist))+geom_line()
ggplot(data=economics, aes(x=date, y=unemploy)) + geom_line()
ggplot(data=economics, aes(x=date, y=psavert)) + geom_line()
ggplot() + 
geom_line(data=economics,aes(x=date, y=uempmed, color="red")) +  geom_line(data=economics, aes(x=date, y=psavert))
```

## 함수를 정교하게 그리기
```{r}
ggplot(data = diamonds, aes(x=carat, y=price, col = cut)) + geom_point()
```

- 막대그래프 2개 범주 내용 반영하기
```{r}
ggplot(diamonds, aes(x=color, fill = cut)) + geom_bar()
ggplot(diamonds, aes(x=color, fill = cut)) + geom_bar(position = "dodge")
ggplot(diamonds, aes(x=color, fill = cut)) + geom_bar(position = "fill")
```

- 선 그래프에 2개 범주 내용 반영
```{r}
leisure <- read.csv("data/leisure.csv")
str(leisure)
```
```{r}
ggplot(data = leisure, aes(x=age, y=expense)) + geom_line()
ggplot(data = leisure, aes(x=age, y=expense, col=sex)) + geom_line()
```
### 막대 그래프의 순서 변경
-reorder()
```{r}
mpg1 <- read.csv("data/mpg1.csv", stringsAsFactors = FALSE)

drv_hwy <- mpg1 %>% 
  group_by(drv) %>% 
  summarise(mean_hwy=mean(hwy))
```
```{r}
ggplot(data = drv_hwy, aes(x = drv, 
                           y= mean_hwy)) + geom_col()
ggplot(data = drv_hwy, aes(x = reorder(drv, mean_hwy), #오름차순
                           y= mean_hwy)) + geom_col()
ggplot(data = drv_hwy, aes(x = reorder(drv, -mean_hwy), #내림차순
                           y= mean_hwy)) + 
  geom_col() + 
  labs(
  title = "그래프의 제목을 입력하세요.",
  subtitle = "그래프의 소제목을 입력하세요.",
  x = "x변수명을 입력하세요.",
  y = "y변수명을 입력하세요.",
  caption= "데이터 출처를 입력하세요.")
```

