---
title: "그래프 옵션"
output:
  html_document:
    toc: true
    toc_float: true
    keep_md: true
date: '2022-06-23 10:00:00'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 제목 변경
- 아래와 같이 작성 시 md 파일 왼쪽에 빠르게 찾아가기가 생성된다.
  
  + title: ""
    output:
     html_document:
      toc: true
      toc_float: true
      keep_md: true
    date: '2022-06-23 10:00:00

## 그래프 복습

iris 데이터, sepal.length, sepal.width 활용해서 종별로 산점도를 그리세요.
(제목과 x축, y축 제목을 변경하세요
  + x축 길이, y축 너비)
```{r}
#install.packages("ggplot2")
library(ggplot2)
str(iris)
ggplot(iris, aes(x = Sepal.Length, y=Sepal.Width, 
                 #종별 산점도
                colour = Species)) +
  geom_point() +
  labs (title = "제목",
    x = "길이",
    y = "너비"
  )

#옵션 추가
ggplot(iris, aes(x = Sepal.Length, y=Sepal.Width, 
                 #종별 산점도
                colour = Species)) +
  geom_point() +
  labs (title = "제목",
    x = "길이",
    y = "너비"
  ) + # 종별로 다른색 칠하기
  scale_color_manual(labels = c("setosa", "versicolor", "virginica"),
                     values = c("red", "blue", "yellow")) +
  # 그래프 테마 바꾸기
  theme_classic()

str(economics)
ggplot(economics, aes(x=pop, y=psavert)) + geom_point()

```

ggplot2 사이트 참고(https://exts.ggplot2.tidyverse.org/gallery/)


